version: "3.8"

services:
  flask_app:
    image: ${DOCKER_IMAGE:-afnankhan03/flask-mongo-app}:${DOCKER_TAG:-latest}
    container_name: jenkins_flask_mongo_app
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=${MONGO_URI:-mongodb+srv://afnan:afnan@cluster0.jv1iq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      - SECRET_KEY=${SECRET_KEY:-ba9c73147efc5cf66b15a55e32410ef7cf1e4da81fa7a8391ada00da3c8b30c9}
      - FLASK_APP=app.py
      - PYTHONPATH=/app
    working_dir: /app
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.2
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
