version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_crud_pipeline_app
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=mongodb+srv://afnan:afnan@cluster0.jv1iq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - SECRET_KEY=ba9c73147efc5cf66b15a55e32410ef7cf1e4da81fa7a8391ada00da3c8b30c9
