version: "3.8"

services:
  flask_app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    container_name: ${PROJECT_NAME}_app
    ports:
      - "5050:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app
    working_dir: /app
    restart: unless-stopped
